#!/usr/bin/env bash

read -p "Are you sure you want to push Klipper configuration? [yN]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  rsync -a klipper-config/ender3v2 ender3v2.local:~/printer_data/config/
  rsync -a klippy-extras/ ender3v2.local:~/klipper/klippy/extras/
fi
